**Numpy**

* Numpy -> Numeric Python
* Listelerden 50 kata kadar daha hızlı
* Çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* veri tipleri homoje yapıda olmalıdır. Tüm elemanlar aynı veri tipinde olmalı
* Numpy dizilerinin veri tipi ndarray dir


pip install numpy

np.__version__

In [13]:
import numpy as np

In [3]:
nd = np.array([1,2,3,4,6,7,8]) #list

print(nd)

[1 2 3 4 6 7 8]


In [4]:
print(type(nd))

<class 'numpy.ndarray'>


In [5]:
nd = np.array((1,2,3,4,6,7,8)) #tuple

print(nd)

[1 2 3 4 6 7 8]


O Boyutlu Diziler

In [6]:
nd = np.array(48)

print(nd)

48


1-D diziler

In [7]:
nd = np.array([1,2,3,4,6,7,8])

print(nd)

[1 2 3 4 6 7 8]


2-D diziler

In [8]:
nd_2d = np.array([[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]])

print(nd_2d)

[[1 2 3 4 6 7 8]
 [1 2 3 4 6 7 8]]


3-D Diziler

In [9]:
nd_3d = np.array([[[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]], [[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]]])

print(nd_3d)

[[[1 2 3 4 6 7 8]
  [1 2 3 4 6 7 8]]

 [[1 2 3 4 6 7 8]
  [1 2 3 4 6 7 8]]]


Boyut bulma -> ndim

In [8]:
nd = np.array([1,2,3,4,6,7,8])
nd_2d = np.array([[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]])
nd_3d = np.array([[[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]], [[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]]])


print(nd.ndim)
print(nd_2d.ndim)
print(nd_3d.ndim)

1
2
3


In [9]:
nd = np.array([1,2,3], ndmin=2)

print(nd)
print(nd.ndim)

[[1 2 3]]
2


shape -> dizinin satır sütun sayısını verir

In [10]:
nd = np.array([1,0,3,4,8])
nd_2d = np.array([[1,2,0,3,4,6], [4,5,7,8,4,9]])

print("1 boyutlu dizi  ",nd.shape)
print("2 boyutlu dizi  ",nd_2d.shape)

1 boyutlu dizi   (5,)
2 boyutlu dizi   (2, 6)


.reshape() -> dizinin satır ve sütun değerlerini değiştirir

In [24]:
nd = np.array([1,2,3,4,5,6,7,8,9,10])

print(nd.shape)
print("\n2X5")
print(nd.reshape(2, 5))
print("\n5X2")
print(nd.reshape(5, 2))

(10,)

2X5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

5X2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


np.arange()

[start, end, step]

In [25]:
nd = np.arange(0,10,2)

print(nd)

[0 2 4 6 8]


**Dizi elemanlarına erişim**

In [11]:
#1-D dizilerde erişim
nd = np.arange(0,11,3)

print(nd)
print(nd[2])

[0 3 6 9]
6


In [31]:
#2-D dizilerde erişim
nd_2d = np.array([[1,2,0,3,4,6], [4,5,7,8,4,9]])

print(nd_2d)

#9 elemanına erişim
print(nd_2d[1, 5])

#negatif indexleme
print(nd_2d[1, -1])

[[1 2 0 3 4 6]
 [4 5 7 8 4 9]]
9
9


In [33]:
#3-D dizilerde erişim
nd_3d = np.array([[[1,2,3], [4,6,7]], [[3,4,6], [6,7,8]]])

print(nd_3d)
print(nd_3d[0, 1, 2])

[[[1 2 3]
  [4 6 7]]

 [[3 4 6]
  [6 7 8]]]
7


NumPy Slicing

[start, end, step]

In [34]:
nd = np.array([1,2,3,4,5,6,7,8,9,10])

print(nd[:4])

[1 2 3 4]


In [37]:
nd_2d = np.array([[1,2,0,3,4,6], [4,5,7,8,4,9], [3,5,6,8,9,0]])

print(nd_2d[0:2, 1:4])

[[2 0 3]
 [5 7 8]]


In [38]:
print(nd_2d.dtype)

int32


0 matrisi oluşturma -> np.zeros()

In [43]:
print(np.zeros((4, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


np.ones() -> 1 lerden oluşan bir matris döner

In [44]:
print(np.ones((4, 5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


np.eye() -> Belirlenen boyutlarda birim matris oluşturmamızı sağlar

In [46]:
print(np.eye(5)) #np.eye(5,5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


np.random() -> İstenilen boyutta bir dizi oluşturur ve bu diziyi 0 ve 1 aralığında rastgele sayılar ile doldurur

In [14]:
nd = np.random.random((3, 2))

nd

array([[0.98348141, 0.62741672],
       [0.19373348, 0.90055722],
       [0.26850709, 0.04044001]])

linspace() -> iki değer arasında eşit oranlı değer oluşturur

In [15]:
nd = np.linspace(5, 6, num = 5)

nd

array([5.  , 5.25, 5.5 , 5.75, 6.  ])

In [16]:
#num kullanmadan da yazılabilir
nd = np.linspace(5, 6, 5)

nd

array([5.  , 5.25, 5.5 , 5.75, 6.  ])

In [17]:
#bitiş değerini dahil etmek istemezsek endpoint=False u kullanırız.
nd = np.linspace(5, 6, 5, endpoint=False)

nd

array([5. , 5.2, 5.4, 5.6, 5.8])

Full -> istenilen satır ve sütunda bir matrisi istediğimiz değer ile doldurur. 2 parametre alır. İlk parametre kaça kaç olacağı ikinci parametre de hangi değerle dolduracağımız bilgisini ekleriz.

In [18]:
nd = np.full((3, 4), 8)

nd

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

**All** -> tüm elemanların verilen şartı sağlayıp sağlamadığını kontrol etmek için kullanırız

In [20]:
nd = np.array([1,2,34,5,6])

np.all(nd > 0)

True

**any()** -> Herhangi bir elemanın verilen şartı sağlayıp sağlamadığını kontrol etmek için kullanırız

In [21]:
nd = np.array([1,2,-1,5,6])

np.any(nd < 0)

True

**Matrisleri Birleştirmek** -> concatenate()

In [24]:
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])

nd3 = np.concatenate([nd1, nd2])

nd3

array([1, 2, 3, 4, 5, 6])

2 numpy array + list

In [25]:
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])
my_list = [1,2,3]

nd3 = np.concatenate([nd1, nd2, my_list])

nd3

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [29]:
nd1 = np.array([1,2,3])
nd2 = np.array([4,5,6])

#satır bazlı birleştirme
print(np.concatenate([nd1, nd2], axis=0)) #axis=0 yazmak zorunda değiliz

[1 2 3 4 5 6]


In [35]:
nd1 = np.array([[1,2,0], [4,5,7]])
nd2 = np.array([[3,4,6], [8,9,0]])

#sütun bazlı birleştirme
print(np.concatenate([nd1, nd2], axis = 1))

#satır bazlı birleştirme
print(np.concatenate([nd1, nd2]))

[[1 2 0 3 4 6]
 [4 5 7 8 9 0]]
[[1 2 0]
 [4 5 7]
 [3 4 6]
 [8 9 0]]


**Numpy ile matematiksel işlemler**

* sum
* max
* min
* mean
* median
* varyans
* standart sapma

In [36]:
my_list = [0,1,2,3,4,5,6,7,8,9]

nd = np.array(my_list)
nd = nd.reshape(5, 2)

nd

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

Sum

In [37]:
print("Satır Bazlı Toplama: ", nd.sum(axis=1))
print("Sütun Bazlı Toplama: ", nd.sum(axis=0))

Satır Bazlı Toplama:  [ 1  5  9 13 17]
Sütun Bazlı Toplama:  [20 25]


max

In [38]:
print(nd.max())

9


min

In [39]:
print(nd.min())

0


mean() -> Ortalama

In [40]:
print(nd.mean())

4.5


Standart sapma -> bir dizindeki verilerin ortalamaya göre dağılımın sayısal olarak gösterimidir.

In [42]:
print(nd.std())

2.8722813232690143


varyans -> standart sapmanın karesidir.

In [43]:
print(nd.var())

8.25


Aritmetik İşlemler

In [54]:
nd1 = np.array([[1,2,3], [4,5,7]])
nd2 = np.array([[3,4,6], [8,9,5]])

In [55]:
nd1

array([[1, 2, 3],
       [4, 5, 7]])

In [56]:
nd2

array([[3, 4, 6],
       [8, 9, 5]])

Toplama işlemini + operatörü ve add metodu ile yaparız

In [57]:
print(nd1 + nd2)

[[ 4  6  9]
 [12 14 12]]


In [58]:
print(np.add(nd1, nd2))

[[ 4  6  9]
 [12 14 12]]


Çıkarma işlemini - operatörü ve subtract metodu ile yaparız

In [59]:
print(nd2 - nd1)

[[ 2  2  3]
 [ 4  4 -2]]


In [60]:
print(np.subtract(nd2, nd1))

[[ 2  2  3]
 [ 4  4 -2]]


Çarpma işlemini * operatörü ve multiply metodu ile yaparız

In [61]:
print(nd1 * nd2)

[[ 3  8 18]
 [32 45 35]]


In [62]:
print(np.multiply(nd1, nd2))

[[ 3  8 18]
 [32 45 35]]


Bölme işlemi / operatörü ve divide metodu ile yaparız

In [63]:
print(nd2 / nd1)

[[3.         2.         2.        ]
 [2.         1.8        0.71428571]]


In [64]:
print(np.divide(nd2, nd1))

[[3.         2.         2.        ]
 [2.         1.8        0.71428571]]


In [69]:
nd = np.ones((3,4))

nd * 4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

Matrislerin çarpımı

@ ve dot fonksiyonunu kullanıyoruz. Unutulmaması gereken nokta ilk matrisin sütun sayısı ikinci matrisin satır sayısına eşit olmalı

In [71]:
nd = np.arange(0, 10)
nd1 = nd.reshape(5,2)
nd2 = nd.reshape(2,5)
nd

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
nd1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [73]:
nd2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
print(np.dot(nd1, nd2))

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [75]:
print(nd1@nd2)

[[  5   6   7   8   9]
 [ 15  20  25  30  35]
 [ 25  34  43  52  61]
 [ 35  48  61  74  87]
 [ 45  62  79  96 113]]


In [76]:
np.matmul(nd1,nd2)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

Matrisin Transpozu -> Satırları sütun, sütunları satır yapma işlemi -> .T

In [78]:
nd = np.arange(0, 10)
nd1 = nd.reshape(5,2)

nd1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [79]:
nd1.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [86]:
nd_3d = np.array([[[1,2,3,4,6,7,8], [9,10,11,12,13,14,15]], [[16,26,36,46,66,76,86], [13,32,33,43,63,37,38]]])

nd_3d

array([[[ 1,  2,  3,  4,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15]],

       [[16, 26, 36, 46, 66, 76, 86],
        [13, 32, 33, 43, 63, 37, 38]]])

In [87]:
nd_3d.T

array([[[ 1, 16],
        [ 9, 13]],

       [[ 2, 26],
        [10, 32]],

       [[ 3, 36],
        [11, 33]],

       [[ 4, 46],
        [12, 43]],

       [[ 6, 66],
        [13, 63]],

       [[ 7, 76],
        [14, 37]],

       [[ 8, 86],
        [15, 38]]])