**Numpy**

* Numpy -> Numeric Python
* Listelerden 50 kata kadar daha hızlı
* Çok boyutlu arrayler ve matrisler üzerinde yüksek performanslı çalışma imkanı sağlar.
* veri tipleri homoje yapıda olmalıdır. Tüm elemanlar aynı veri tipinde olmalı
* Numpy dizilerinin veri tipi ndarray dir


pip install numpy

np.__version__

In [3]:
import numpy as np

In [4]:
nd = np.array([1,2,3,4,6,7,8]) #list

print(nd)

[1 2 3 4 6 7 8]


In [2]:
print(type(nd))

<class 'numpy.ndarray'>


In [5]:
nd = np.array((1,2,3,4,6,7,8)) #tuple

print(nd)

[1 2 3 4 6 7 8]


O Boyutlu Diziler

In [6]:
nd = np.array(48)

print(nd)

48


1-D diziler

In [7]:
nd = np.array([1,2,3,4,6,7,8])

print(nd)

[1 2 3 4 6 7 8]


2-D diziler

In [8]:
nd_2d = np.array([[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]])

print(nd_2d)

[[1 2 3 4 6 7 8]
 [1 2 3 4 6 7 8]]


3-D Diziler

In [9]:
nd_3d = np.array([[[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]], [[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]]])

print(nd_3d)

[[[1 2 3 4 6 7 8]
  [1 2 3 4 6 7 8]]

 [[1 2 3 4 6 7 8]
  [1 2 3 4 6 7 8]]]


Boyut bulma -> ndim

In [10]:
nd = np.array([1,2,3,4,6,7,8])
nd_2d = np.array([[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]])
nd_3d = np.array([[[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]], [[1,2,3,4,6,7,8], [1,2,3,4,6,7,8]]])


print(nd.ndim)
print(nd_2d.ndim)
print(nd_3d.ndim)

1
2
3


In [13]:
nd = np.array([1,2,3], ndmin=2)

print(nd)
print(nd.ndim)

[[1 2 3]]
2


shape -> dizinin satır sütun sayısını verir

In [15]:
nd = np.array([1,0,3,4,8])
nd_2d = np.array([[1,2,0,3,4,6], [4,5,7,8,4,9]])

print("1 boyutlu dizi  ",nd.shape)
print("2 boyutlu dizi  ",nd_2d.shape)

1 boyutlu dizi   (5,)
2 boyutlu dizi   (2, 6)


.reshape() -> dizinin satır ve sütun değerlerini değiştirir

In [24]:
nd = np.array([1,2,3,4,5,6,7,8,9,10])

print(nd.shape)
print("\n2X5")
print(nd.reshape(2, 5))
print("\n5X2")
print(nd.reshape(5, 2))

(10,)

2X5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]

5X2
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


np.arange()

[start, end, step]

In [25]:
nd = np.arange(0,10,2)

print(nd)

[0 2 4 6 8]


Dizi elemanlarına erişim

In [28]:
#1-D dizilerde erişim
nd = np.arange(0,11,3)

print(nd[2])

6


In [31]:
#2-D dizilerde erişim
nd_2d = np.array([[1,2,0,3,4,6], [4,5,7,8,4,9]])

print(nd_2d)

#9 elemanına erişim
print(nd_2d[1, 5])

#negatif indexleme
print(nd_2d[1, -1])

[[1 2 0 3 4 6]
 [4 5 7 8 4 9]]
9
9


In [33]:
#3-D dizilerde erişim
nd_3d = np.array([[[1,2,3], [4,6,7]], [[3,4,6], [6,7,8]]])

print(nd_3d)
print(nd_3d[0, 1, 2])

[[[1 2 3]
  [4 6 7]]

 [[3 4 6]
  [6 7 8]]]
7


NumPy Slicing

[start, end, step]

In [34]:
nd = np.array([1,2,3,4,5,6,7,8,9,10])

print(nd[:4])

[1 2 3 4]


In [37]:
nd_2d = np.array([[1,2,0,3,4,6], [4,5,7,8,4,9], [3,5,6,8,9,0]])

print(nd_2d[0:2, 1:4])

[[2 0 3]
 [5 7 8]]


In [38]:
print(nd_2d.dtype)

int32


0 matrisi oluşturma -> np.zeros()

In [43]:
print(np.zeros((4, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


np.ones() -> 1 lerden oluşan bir matris döner

In [44]:
print(np.ones((4, 5)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


np.eye() -> Belirlenen boyutlarda birim matris oluşturmamızı sağlar

In [46]:
print(np.eye(5)) #np.eye(5,5)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
